### ISSUE TITLE
Universes PlaceHolder.jar not loading

### ISSUE THREAD

**Issue by GitNuck** [DSlyDog/Universes-Rewritten#11]
Bug description: Plugin 'UniversesPlaceholders.jar' fails to load
Minecraft version: 1.19.3
Server program (spigot, paper, etc): Purpur
Server program version: 1933
Plugin version: Latest
Steps to reproduce and/or video of the bug: Try loading the jar
Logs and error reports: See Attached File

**Comment by GitNuck** [comment]
Found placeholders.jar on Spigot and loaded it from there.

**Comment by DSlyDog** [comment]
Hi! Yes, sorry I'm so late to respond. The UniversesPlaceholders.jar is not meant to be in the plugins folder. It is meant for the PlaceholderAPI extensions folder. I believe I explained in the Universes 5.0 update video I created and in the update post, and I think in the overview somewhere, this was explained. I think I will repackage the jars so that people do not keep running into this in the future.
